datagrids:
    diglin-sms-campaign-grid:
        extended_entity_name: Diglin\Bundle\SmsCampaignBundle\Entity\SmsCampaign
        acl_resource: diglin_sms_campaign_view
        source:
            type: orm
            query:
                select:
                    - ec.id
                    - ec.sent
                    - ec.sentAt
                    - ec.name
                    - ec.schedule
                    - ec.scheduledFor
                    - ec.createdAt
                    - ec.updatedAt
                    - c.name as campaignName
                    - ml.name as marktingListName
                from:
                    - { table: Diglin\Bundle\SmsCampaignBundle\Entity\SmsCampaign, alias: ec }
                join:
                    left:
                        - { join: ec.campaign, alias: c }
                        - { join: ec.marketingList, alias: ml }
        columns:
            name:
                label: oro.campaign.emailcampaign.name.label
            campaignName:
                label: oro.campaign.emailcampaign.campaign.label
            marktingListName:
                label: oro.campaign.emailcampaign.marketing_list.label
            schedule:
                label: oro.campaign.emailcampaign.schedule.label
                type:          twig
                frontend_type: html
                template:      OroCampaignBundle:EmailCampaign:Property/schedule.html.twig
            scheduledFor:
                label: oro.campaign.emailcampaign.scheduled_for.label
                frontend_type: datetime
            sent:
                label:         oro.campaign.emailcampaign.sent.label
                frontend_type: boolean
            sentAt:
                label:         oro.campaign.emailcampaign.sent_at.label
                frontend_type: datetime
            createdAt:
                label: oro.campaign.emailcampaign.created_at.label
                frontend_type: datetime
            updatedAt:
                label: oro.campaign.emailcampaign.updated_at.label
                frontend_type: datetime
        filters:
            columns:
                name:
                    type:        string
                    data_name:   ec.name
                campaignName:
                    type:        string
                    data_name:   c.name
                marktingListName:
                    type:        string
                    data_name:   ml.name
                schedule:
                    type:        choice
                    data_name:   ec.schedule
                    options:
                        field_options:
                            choices:
                                Manual: manual
                                Deferred: deferred
                scheduledFor:
                    type:        datetime
                    data_name:   ec.scheduledFor
                sent:
                    type:        boolean
                    data_name:   ec.sent
                sentAt:
                    type:        datetime
                    data_name:   ec.sentAt
                createdAt:
                    type:        datetime
                    data_name:   ec.createdAt
                updatedAt:
                    type:        datetime
                    data_name:   ec.updatedAt
        sorters:
            columns:
                name:             { data_name: ec.name }
                campaignName:     { data_name: c.name }
                marktingListName: { data_name: ml.name }
                schedule:         { data_name: ec.schedule }
                sent:             { data_name: ec.sent }
                sentAt:           { data_name: ec.sentAt }
                scheduledFor:     { data_name: ec.scheduledFor }
                createdAt:        { data_name: ec.createdAt }
                updatedAt:        { data_name: ec.updatedAt }
            default:
                name: ASC
        properties:
            id: ~
            view_link:
                type: url
                route: diglin_sms_campaign_view
                params: [ id ]
            update_link:
                type: url
                route: diglin_sms_campaign_update
                params: [ id ]
        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye
                acl_resource: diglin_sms_campaign_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  diglin_sms_campaign_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
        options:
            entity_pagination: true

    diglin-sms-campaign-marketing-list-unsent-items-mixin:
        source:
            query:
                join:
                    left:
                        -
                            join: 'Oro\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem'
                            alias: 'mlr'
                            conditionType: 'WITH'
                            condition: 'mlr.entityId = __root_entity__.id AND mlr.marketingList = :marketingListEntity'
                        -
                            join: 'Oro\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem'
                            alias: 'mlu'
                            conditionType: 'WITH'
                            condition: 'mlu.entityId = __root_entity__.id AND mlu.marketingList = :marketingListEntity'
                where:
                    and:
                        - mlr.id IS NULL
                        - mlu.id IS NULL

    diglin-sms-campaign-marketing-list-sent-items-mixin:
        source:
            query:
                select:
                    - cs.bounceCount as bounceCount
                join:
                    inner:
                        -
                            join: 'Oro\Bundle\MarketingListBundle\Entity\MarketingListItem'
                            alias: 'mli'
                            conditionType: 'WITH'
                            condition: 'mli.entityId = __root_entity__.id AND mli.marketingList = :marketingListEntity'
                        -
                            join: 'Diglin\Bundle\SmsCampaignBundle\Entity\SmsCampaignStatistics'
                            alias: 'cs'
                            conditionType: 'WITH'
                            condition: 'cs.marketingListItem = mli.id AND cs.smsCampaign = :smsCampaign'
            bind_parameters:
                - smsCampaign
        columns:
            bounceCount:
                label: oro.campaign.emailcampaign.stats.bounce.label
                type: twig
                frontend_type: html
                template: SmsCampaignBundle:SmsCampaign:Property/stats.html.twig
        filters:
            columns:
                bounceCount:
                    type:        number-range
                    data_name:   cs.bounceCount
        sorters:
            columns:
                bounceCount:      { data_name: cs.bounceCount }
