navigation:
    menu_config:
        items:
            sms_campaigns_list:
                label:    'diglin.campaign.smscampaign.entity_plural_label'
                route:    'diglin_sms_campaign_index'
                extras:
                    routes: ['diglin_sms_campaign_*']
        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            sms_campaigns_list: ~

    titles:
        diglin_sms_campaign_index:  ~
        diglin_sms_campaign_view:   '%entity.name%'
        diglin_sms_campaign_create: 'oro.ui.create_entity'
        diglin_sms_campaign_update: '%entity.name% - Edit'
